# This Dockerfile is optional if you want to add OS-level dependencies.
# Start from the recommended Node.js image.
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20

# [Optional] Install additional OS packages.
# RUN apt-get update && apt-get install -y your-package
